version: v1alpha1
cluster:
  kubeContext: minikube
  namespace: test
devSpace:
  deployments:
  - helm:
      chartPath: ./chart
    name: devspace-default
  ports:
  - labelSelector:
      release: devspace-default
    portMappings:
    - localPort: 8080
      remotePort: 8080
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-default
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
images:
  default:
    build:
      kaniko:
        cache: true
    name: devspace
    registry: internal
internalRegistry:
  deploy: true
