cluster:
  cloudProvider: devspace-cloud
devSpace:
  deployments:
  - helm:
      chartPath: ./chart
    name: devspace-default
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-default
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - node_modules/
images:
  default:
    name: gentele/devspace-cli-docs
    tag: stable
    build:
      disabled: true
version: v1alpha1
