apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        revision: "{{ .Release.Revision }}"
      labels:
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: default
        image: "{{ .Values.containers.php.image }}"
      imagePullSecrets:
        {{- range $index, $secretName := .Values.pullSecrets }}
        - name: "{{ $secretName }}"
        {{- end }}
